# -*- coding: utf-8 -*-
"""worker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E67C9zSJo4scjnZzrAu4nStDkkgD-0ld
"""

# worker.py

import os
from redis import Redis
from rq import Worker, Queue, Connection

listen = ['default']
redis_url = os.getenv('REDIS_URL', 'redis://localhost:6379')
conn = Redis.from_url(redis_url)

if __name__ == '__main__':
    with Connection(conn):
        worker = Worker(map(Queue, listen))
        worker.work()